version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432" # Mapeamento da porta do contêiner PostgreSQL para a máquina host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume para persistir os dados do PostgreSQL
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: teste-pratico-vrsoftware-postgres

  springboot:
    image: openjdk:latest # Imagem base para o Spring Boot
    ports:
      - "8081:8080" # Mapeamento da porta 8080 do contêiner Spring Boot para a máquina host
    volumes:
      - ./coremastermarket.jar:/app/coremastermarket.jar # Mapeamento do JAR Spring Boot para dentro do contêiner
    command: ["java", "-jar", "/app/coremastermarket.jar"]
    depends_on:
      - postgres # Garanta que o contêiner PostgreSQL esteja pronto antes de iniciar o Spring Boot
    container_name: teste-pratico-vrsoftware-springboot

volumes:
  postgres_data:
