package CoreMasterMarket.gui;

import CoreMasterMarket.DefinicaoOS;
import CoreMasterMarket.config.ConfigReal;
import CoreMasterMarket.service.ClientesService;
import CoreMasterMarket.service.PDVService;
import CoreMasterMarket.service.ProdutoService;
import CoreMasterMarket.service.VendasService;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author rodolfobrandao
 */
public class App extends javax.swing.JFrame {

    private CardLayout cardLayout;
//    static PDVService pdvService = new PDVService();

    private String urlAPI = ConfigReal.urlAPI;
    private String tokenAPI = ConfigReal.token;
    private String userId = ConfigReal.userId;
    private String userLogin = ConfigReal.userLogin;
    private String userPassword = ConfigReal.userPassword;
    private String userRole = ConfigReal.userRole;
    private String userName = ConfigReal.userName;
    private String userFullname = ConfigReal.userFullname;
    private String userUsername = ConfigReal.userUsername;
    private String userProfileImg = ConfigReal.userProfileImg;
//    private JList<String> listSuggestions;

    public App() {

        initComponents();
        App.this.getRootPane().setBorder(new LineBorder(new Color(255, 51, 51)));
        lblTitle.setText(this.getTitle());
        cardLayout = (CardLayout) pnlRight.getLayout();
        ExecutarDadosUser();

        if (DefinicaoOS.getOSType() == DefinicaoOS.OSType.MacOS) {
            pnlTop.remove(pnlTitle);
            pnlTop.remove(pnlRight);

            pnlTop.add(pnlTitle, BorderLayout.EAST);
            pnlTop.add(pnlActions, BorderLayout.WEST);

            pnlActions.remove(lblClose);
            pnlActions.remove(lblMaximize);
            pnlActions.remove(lblMinimize);

            pnlActions.add(lblClose);
            pnlActions.add(lblMaximize);
            pnlActions.add(lblMinimize);

            pnlTitle.remove(lblTitle);
            pnlTitle.setLayout(new FlowLayout(FlowLayout.RIGHT, 10, 8));
            pnlTitle.add(lblTitle);

        }
        if (DefinicaoOS.getOSType() == DefinicaoOS.OSType.Windows) {
            pnlTop.remove(pnlTitle);
            pnlTop.remove(pnlRight);

            pnlTop.add(pnlTitle, BorderLayout.WEST);
            pnlTop.add(pnlActions, BorderLayout.EAST);

            pnlActions.remove(lblClose);
            pnlActions.remove(lblMaximize);
            pnlActions.remove(lblMinimize);

            pnlActions.add(lblMinimize);
            pnlActions.add(lblMaximize);
            pnlActions.add(lblClose);

            pnlTitle.remove(lblTitle);
            pnlTitle.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 8));
            pnlTitle.add(lblTitle);
        }
    }

    public void ExecutarDadosUser() {
        NomeAtendenteCaixa.setText(userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        pnlActions = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblMaximize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlParent = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btn_typo = new javax.swing.JPanel();
        ind_typo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jBtClientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_produto = new javax.swing.JPanel();
        ind_data1 = new javax.swing.JPanel();
        jLabel7Cadastro = new javax.swing.JLabel();
        btn_pdv = new javax.swing.JPanel();
        ind_data = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7PRODUTOS = new javax.swing.JLabel();
        jLabel7PDV = new javax.swing.JLabel();
        btn_produtos = new javax.swing.JPanel();
        ind_btns = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jBtProdutoss = new javax.swing.JButton();
        NomeAtendenteCaixa = new javax.swing.JLabel();
        btn_vendas = new javax.swing.JPanel();
        ind_data2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jBtVendas = new javax.swing.JButton();
        pnlRight = new javax.swing.JPanel();
        Display1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        DisplayIncial = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        background1 = new javax.swing.JLabel();
        Display3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbAddProduto = new javax.swing.JButton();
        jbAddProduto1 = new javax.swing.JButton();
        jbAddProduto2 = new javax.swing.JButton();
        jbAddProduto3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistCadastros = new javax.swing.JList<>();
        Display2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lbl_instals1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel do gestor");
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 760));

        pnlTop.setBackground(new java.awt.Color(255, 51, 51));
        pnlTop.setPreferredSize(new java.awt.Dimension(1024, 30));
        pnlTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTopMouseDragged(evt);
            }
        });
        pnlTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTopMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTopMousePressed(evt);
            }
        });
        pnlTop.setLayout(new java.awt.BorderLayout());

        pnlActions.setBackground(new java.awt.Color(255, 51, 0));
        pnlActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/imgs/iconminimizar.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        pnlActions.add(lblMinimize);

        lblMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/imgs/iconmaximizar.png"))); // NOI18N
        lblMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMaximizeMousePressed(evt);
            }
        });
        pnlActions.add(lblMaximize);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/imgs/iconfechar.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        pnlActions.add(lblClose);

        pnlTop.add(pnlActions, java.awt.BorderLayout.LINE_END);

        pnlTitle.setBackground(new java.awt.Color(255, 51, 0));
        pnlTitle.setPreferredSize(new java.awt.Dimension(200, 30));
        pnlTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 8));

        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Painel do gestor");
        lblTitle.setToolTipText("");
        pnlTitle.add(lblTitle);

        pnlTop.add(pnlTitle, java.awt.BorderLayout.LINE_START);

        getContentPane().add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlParent.setLayout(new java.awt.BorderLayout());

        sidepane.setBackground(new java.awt.Color(255, 51, 0));
        sidepane.setForeground(new java.awt.Color(51, 51, 51));
        sidepane.setPreferredSize(new java.awt.Dimension(250, 200));
        sidepane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidepaneMouseDragged(evt);
            }
        });
        sidepane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidepaneMousePressed(evt);
            }
        });

        btn_typo.setBackground(new java.awt.Color(255, 102, 0));
        btn_typo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_typoMouseMoved(evt);
            }
        });
        btn_typo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_typoMousePressed(evt);
            }
        });
        btn_typo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_typo.setOpaque(false);
        ind_typo.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_typoLayout = new javax.swing.GroupLayout(ind_typo);
        ind_typo.setLayout(ind_typoLayout);
        ind_typoLayout.setHorizontalGroup(
            ind_typoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_typoLayout.setVerticalGroup(
            ind_typoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_typo.add(ind_typo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/vr-cores/cliente64.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("CoreMasterMarket/gui/Bundle"); // NOI18N
        jLabel12.setText(bundle.getString("App.jLabel12.text")); // NOI18N
        jLabel12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel12KeyPressed(evt);
            }
        });
        btn_typo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 70));

        jBtClientes.setBackground(new java.awt.Color(255, 102, 0));
        jBtClientes.setText(bundle.getString("App.jBtClientes.text")); // NOI18N
        jBtClientes.setBorder(null);
        jBtClientes.setBorderPainted(false);
        jBtClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtClientesActionPerformed(evt);
            }
        });
        jBtClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtClientesKeyPressed(evt);
            }
        });
        btn_typo.add(jBtClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 250, 70));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(bundle.getString("App.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teste Prátrico VR-Software");

        btn_produto.setBackground(new java.awt.Color(255, 51, 0));
        btn_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_produtoMousePressed(evt);
            }
        });
        btn_produto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_data1.setOpaque(false);
        ind_data1.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_data1Layout = new javax.swing.GroupLayout(ind_data1);
        ind_data1.setLayout(ind_data1Layout);
        ind_data1Layout.setHorizontalGroup(
            ind_data1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_data1Layout.setVerticalGroup(
            ind_data1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_produto.add(ind_data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel7Cadastro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7Cadastro.setText("CADASTRO");

        btn_pdv.setBackground(new java.awt.Color(255, 51, 0));
        btn_pdv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_pdvMousePressed(evt);
            }
        });
        btn_pdv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_data.setOpaque(false);
        ind_data.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_dataLayout = new javax.swing.GroupLayout(ind_data);
        ind_data.setLayout(ind_dataLayout);
        ind_dataLayout.setHorizontalGroup(
            ind_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_dataLayout.setVerticalGroup(
            ind_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_pdv.add(ind_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/vr-cores/pdv64f.png"))); // NOI18N
        jLabel10.setText(bundle.getString("App.jLabel10.text")); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(512, 512));
        jLabel10.setMinimumSize(new java.awt.Dimension(512, 512));
        jLabel10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel10KeyPressed(evt);
            }
        });
        btn_pdv.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 60));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText(bundle.getString("App.jButton1.text")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        btn_pdv.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 250, 60));

        jLabel7PRODUTOS.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7PRODUTOS.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7PRODUTOS.setText("PRODUTOS");

        jLabel7PDV.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7PDV.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7PDV.setText("PDV");

        btn_produtos.setBackground(new java.awt.Color(255, 51, 0));
        btn_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_produtosMousePressed(evt);
            }
        });
        btn_produtos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_btns.setOpaque(false);
        ind_btns.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_btnsLayout = new javax.swing.GroupLayout(ind_btns);
        ind_btns.setLayout(ind_btnsLayout);
        ind_btnsLayout.setHorizontalGroup(
            ind_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_btnsLayout.setVerticalGroup(
            ind_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_produtos.add(ind_btns, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/vr-cores/produtos64.png"))); // NOI18N
        jLabel14.setText(bundle.getString("App.jLabel14.text")); // NOI18N
        jLabel14.setMaximumSize(new java.awt.Dimension(512, 512));
        jLabel14.setMinimumSize(new java.awt.Dimension(512, 512));
        btn_produtos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 80));

        jBtProdutoss.setBackground(new java.awt.Color(255, 102, 0));
        jBtProdutoss.setText(bundle.getString("App.jBtProdutoss.text")); // NOI18N
        jBtProdutoss.setBorder(null);
        jBtProdutoss.setBorderPainted(false);
        jBtProdutoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtProdutossActionPerformed(evt);
            }
        });
        jBtProdutoss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtProdutossKeyPressed(evt);
            }
        });
        btn_produtos.add(jBtProdutoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 250, 70));

        NomeAtendenteCaixa.setText(bundle.getString("App.NomeAtendenteCaixa.text")); // NOI18N

        btn_vendas.setBackground(new java.awt.Color(255, 51, 0));
        btn_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_vendasMousePressed(evt);
            }
        });
        btn_vendas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_data2.setOpaque(false);
        ind_data2.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_data2Layout = new javax.swing.GroupLayout(ind_data2);
        ind_data2.setLayout(ind_data2Layout);
        ind_data2Layout.setHorizontalGroup(
            ind_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_data2Layout.setVerticalGroup(
            ind_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_vendas.add(ind_data2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/vr-cores/pdv64.png"))); // NOI18N
        jLabel11.setText(bundle.getString("App.jLabel11.text")); // NOI18N
        jLabel11.setMaximumSize(new java.awt.Dimension(512, 512));
        jLabel11.setMinimumSize(new java.awt.Dimension(512, 512));
        jLabel11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel11KeyPressed(evt);
            }
        });
        btn_vendas.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 60));

        jBtVendas.setBackground(new java.awt.Color(255, 102, 0));
        jBtVendas.setText(bundle.getString("App.jBtVendas.text")); // NOI18N
        jBtVendas.setBorderPainted(false);
        jBtVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtVendasActionPerformed(evt);
            }
        });
        jBtVendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtVendasKeyPressed(evt);
            }
        });
        btn_vendas.add(jBtVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 250, 60));

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_typo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepaneLayout.createSequentialGroup()
                        .addComponent(btn_produto, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_pdv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(sidepaneLayout.createSequentialGroup()
                                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7PDV)
                                    .addComponent(jLabel7Cadastro)
                                    .addComponent(jLabel7PRODUTOS))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepaneLayout.createSequentialGroup()
                                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(sidepaneLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(NomeAtendenteCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))))
                                .addGap(23, 23, 23)))))
                .addContainerGap())
            .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidepaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_vendas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeAtendenteCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7Cadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_typo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7PRODUTOS)
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7PDV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
            .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidepaneLayout.createSequentialGroup()
                    .addGap(453, 453, 453)
                    .addComponent(btn_vendas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );

        pnlParent.add(sidepane, java.awt.BorderLayout.LINE_START);

        pnlRight.setLayout(new java.awt.CardLayout());

        Display1.setForeground(new java.awt.Color(255, 255, 255));
        Display1.setToolTipText("");
        Display1.setVerifyInputWhenFocusTarget(false);

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1299, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Display1Layout = new javax.swing.GroupLayout(Display1);
        Display1.setLayout(Display1Layout);
        Display1Layout.setHorizontalGroup(
            Display1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Display1Layout.setVerticalGroup(
            Display1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display1Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pnlRight.add(Display1, "card1");

        DisplayIncial.setPreferredSize(new java.awt.Dimension(1072, 773));
        DisplayIncial.setVerifyInputWhenFocusTarget(false);

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/vr-cores/fundoPDVProduto.png"))); // NOI18N
        background1.setAlignmentY(0.0F);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(background1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DisplayIncialLayout = new javax.swing.GroupLayout(DisplayIncial);
        DisplayIncial.setLayout(DisplayIncialLayout);
        DisplayIncialLayout.setHorizontalGroup(
            DisplayIncialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayIncialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        DisplayIncialLayout.setVerticalGroup(
            DisplayIncialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayIncialLayout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pnlRight.add(DisplayIncial, "card0");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastro Clientes");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Abaixo você pode cadastrar novos clientes:");

        jbAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/imgs/adicionar.png"))); // NOI18N
        jbAddProduto.setText("ADICIONAR");
        jbAddProduto.setAutoscrolls(true);
        jbAddProduto.setMaximumSize(new java.awt.Dimension(64, 64));
        jbAddProduto.setMinimumSize(new java.awt.Dimension(64, 64));
        jbAddProduto.setPreferredSize(new java.awt.Dimension(64, 64));
        jbAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddProdutoActionPerformed(evt);
            }
        });

        jbAddProduto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/imgs/excluir.png"))); // NOI18N
        jbAddProduto1.setText("EXCLUIR");
        jbAddProduto1.setAutoscrolls(true);
        jbAddProduto1.setMaximumSize(new java.awt.Dimension(64, 64));
        jbAddProduto1.setMinimumSize(new java.awt.Dimension(64, 64));
        jbAddProduto1.setPreferredSize(new java.awt.Dimension(64, 64));
        jbAddProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddProduto1ActionPerformed(evt);
            }
        });

        jbAddProduto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/imgs/salvar.png"))); // NOI18N
        jbAddProduto2.setText("SALVAR");
        jbAddProduto2.setAutoscrolls(true);
        jbAddProduto2.setMaximumSize(new java.awt.Dimension(64, 64));
        jbAddProduto2.setMinimumSize(new java.awt.Dimension(64, 64));
        jbAddProduto2.setPreferredSize(new java.awt.Dimension(64, 64));
        jbAddProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddProduto2ActionPerformed(evt);
            }
        });

        jbAddProduto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/imgs/ajuda.png"))); // NOI18N
        jbAddProduto3.setText("EDITAR");
        jbAddProduto3.setAutoscrolls(true);
        jbAddProduto3.setMaximumSize(new java.awt.Dimension(64, 64));
        jbAddProduto3.setMinimumSize(new java.awt.Dimension(64, 64));
        jbAddProduto3.setPreferredSize(new java.awt.Dimension(64, 64));
        jbAddProduto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddProduto3ActionPerformed(evt);
            }
        });

        jlistCadastros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlistCadastros);

        javax.swing.GroupLayout Display3Layout = new javax.swing.GroupLayout(Display3);
        Display3.setLayout(Display3Layout);
        Display3Layout.setHorizontalGroup(
            Display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display3Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(Display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addGroup(Display3Layout.createSequentialGroup()
                        .addGroup(Display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbAddProduto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(jbAddProduto2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAddProduto3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAddProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        Display3Layout.setVerticalGroup(
            Display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(Display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Display3Layout.createSequentialGroup()
                        .addComponent(jbAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAddProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jbAddProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAddProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 435, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pnlRight.add(Display3, "card3");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRODUTOS CADASTRADOS");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Abaixo você pode cadastrar novos clientes:");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbl_instals1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        lbl_instals1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_instals1.setText("10");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("13");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nome:");

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("FIM");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("V0.1");

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Documento:");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Endereço");

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("189");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout Display2Layout = new javax.swing.GroupLayout(Display2);
        Display2.setLayout(Display2Layout);
        Display2Layout.setHorizontalGroup(
            Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel5)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Display2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addGroup(Display2Layout.createSequentialGroup()
                                .addGroup(Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_instals1)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel25))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26))))))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Display2Layout.createSequentialGroup()
                .addContainerGap(1271, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        Display2Layout.setVerticalGroup(
            Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Display2Layout.createSequentialGroup()
                .addGroup(Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Display2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24))
                    .addGroup(Display2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(28, 28, 28)
                        .addGroup(Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Display2Layout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Display2Layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel22))
                                    .addGroup(Display2Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_instals1))
                                    .addGroup(Display2Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel27))))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 516, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        pnlRight.add(Display2, "card2");

        pnlParent.add(pnlRight, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlParent, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xy, xx;

    private void lblMaximizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizeMousePressed
        if (App.this.getExtendedState() == MAXIMIZED_BOTH) {
            App.this.setExtendedState(JFrame.NORMAL);
        } else {
            App.this.setExtendedState(MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_lblMaximizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        App.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void pnlTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnlTopMousePressed

    private void pnlTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnlTopMouseDragged

    private void pnlTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            if (App.this.getExtendedState() == MAXIMIZED_BOTH) {
                App.this.setExtendedState(JFrame.NORMAL);
            } else {
                App.this.setExtendedState(MAXIMIZED_BOTH);
            }
        }
    }//GEN-LAST:event_pnlTopMouseClicked

    private void sidepaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepaneMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidepaneMousePressed

    private void sidepaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepaneMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_sidepaneMouseDragged

    private void btn_pdvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pdvMousePressed
        // TODO add your handling code here:
        setColor(btn_pdv);
        resetColor(btn_typo);
        resetColor(btn_produtos);
//        resetColor(btn_fonts);
//        resetColor(btn_icons);

        ind_typo.setOpaque(false);
        ind_btns.setOpaque(false);
        ind_data.setOpaque(true);
//        ind_fonts.setOpaque(false);
//        ind_icons.setOpaque(false);

        cardLayout.show(pnlRight, "card1");
    }//GEN-LAST:event_btn_pdvMousePressed

    private void btn_produtosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produtosMousePressed
        // TODO add your handling code here:
        setColor(btn_produtos);
        resetColor(btn_pdv);
        resetColor(btn_typo);
//        resetColor(btn_fonts);
//        resetColor(btn_icons);

        ind_typo.setOpaque(false);
        ind_btns.setOpaque(true);
        ind_data.setOpaque(false);
//        ind_fonts.setOpaque(false);
//        ind_icons.setOpaque(false);
        cardLayout.show(pnlRight, "card2");
    }//GEN-LAST:event_btn_produtosMousePressed

    private void btn_produtoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produtoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_produtoMousePressed

    private void btn_typoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_typoMousePressed
        // TODO add your handling code here:

        setColor(btn_typo);
        resetColor(btn_pdv);
        resetColor(btn_produtos);
//        resetColor(btn_fonts);
//        resetColor(btn_icons);
        ind_typo.setOpaque(true);
        ind_btns.setOpaque(false);
        ind_data.setOpaque(false);
//        ind_fonts.setOpaque(false);
//        ind_icons.setOpaque(false);

        cardLayout.show(pnlRight, "card3");
    }//GEN-LAST:event_btn_typoMousePressed

    private void btn_typoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_typoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_typoMouseMoved

    private void jbAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddProdutoActionPerformed

    }//GEN-LAST:event_jbAddProdutoActionPerformed

    private void jbAddProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddProduto1ActionPerformed

    private void jbAddProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddProduto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddProduto2ActionPerformed

    private void jbAddProduto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddProduto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddProduto3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        pdvService.carregarProdutos();
        PDVService telaCardUser = new PDVService();
        panel1.add(telaCardUser);
        telaCardUser.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_F3) {
            // Coloque aqui o código que você quer executar quando a tecla F3 for pressionada
            System.out.println("F3 foi pressionada!");
            PDVService telaCardUser = new PDVService();
            panel1.add(telaCardUser);
            telaCardUser.setVisible(true);
        }

    }//GEN-LAST:event_jButton1KeyPressed

    private void jLabel10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel10KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10KeyPressed

    private void jLabel11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel11KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11KeyPressed

    private void jBtVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtVendasActionPerformed
        VendasService telaCardUser = new VendasService();
        panel1.add(telaCardUser);
        telaCardUser.setVisible(true);

    }//GEN-LAST:event_jBtVendasActionPerformed

    private void jBtVendasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtVendasKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_F4) {
            // Coloque aqui o código que você quer executar quando a tecla F3 for pressionada
            System.out.println("F3 foi pressionada!");
            VendasService telaCardUser = new VendasService();
            panel1.add(telaCardUser);
            telaCardUser.setVisible(true);
        }
    }//GEN-LAST:event_jBtVendasKeyPressed

    private void btn_vendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vendasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vendasMousePressed

    private void jLabel12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel12KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12KeyPressed

    private void jBtClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtClientesActionPerformed
        ClientesService telaCardUser = new ClientesService("Painel Cliente");
        panel1.add(telaCardUser);
        telaCardUser.setVisible(true);
    }//GEN-LAST:event_jBtClientesActionPerformed

    private void jBtClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtClientesKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_F1) {
            // Coloque aqui o código que você quer executar quando a tecla F3 for pressionada
            System.out.println("F3 foi pressionada!");
            ClientesService telaCardUser = new ClientesService("Painel Cliente");
            panel1.add(telaCardUser);
            telaCardUser.setVisible(true);
        }
    }//GEN-LAST:event_jBtClientesKeyPressed

    private void jBtProdutossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtProdutossActionPerformed
            ProdutoService telaCardUser = new ProdutoService();
            panel1.add(telaCardUser);
            telaCardUser.setVisible(true);
    }//GEN-LAST:event_jBtProdutossActionPerformed

    private void jBtProdutossKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtProdutossKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_F2) {
            System.out.println("F2 foi pressionada!");
            ProdutoService telaCardUser = new ProdutoService();
            panel1.add(telaCardUser);
            telaCardUser.setVisible(true);
        }
    }//GEN-LAST:event_jBtProdutossKeyPressed

    // set and reset color
    void setColor(JPanel panel) {
        panel.setBackground(new Color(255, 160, 0));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(255, 102, 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Display1;
    public javax.swing.JPanel Display2;
    public javax.swing.JPanel Display3;
    public javax.swing.JPanel DisplayIncial;
    private javax.swing.JLabel NomeAtendenteCaixa;
    private javax.swing.JLabel background1;
    private javax.swing.JPanel btn_pdv;
    private javax.swing.JPanel btn_produto;
    private javax.swing.JPanel btn_produtos;
    private javax.swing.JPanel btn_typo;
    private javax.swing.JPanel btn_vendas;
    private javax.swing.JPanel ind_btns;
    private javax.swing.JPanel ind_data;
    private javax.swing.JPanel ind_data1;
    private javax.swing.JPanel ind_data2;
    private javax.swing.JPanel ind_typo;
    private javax.swing.JButton jBtClientes;
    private javax.swing.JButton jBtProdutoss;
    private javax.swing.JButton jBtVendas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7Cadastro;
    private javax.swing.JLabel jLabel7PDV;
    private javax.swing.JLabel jLabel7PRODUTOS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jbAddProduto;
    private javax.swing.JButton jbAddProduto1;
    private javax.swing.JButton jbAddProduto2;
    private javax.swing.JButton jbAddProduto3;
    private javax.swing.JList<String> jlistCadastros;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMaximize;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbl_instals1;
    private java.awt.Panel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlParent;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables

}
